// 道具资产登记表（WORKFLOW §3）：显式 import 逐件登记，禁 import.meta.glob。
// 契约测试按 fs 扫描自动发现（过门与登记解耦，支持并行生产）——本表只负责
// 陈列页/房型配方层的可用集合；新资产验收通过后由 orchestrator 按 id 排序插入。

import alcoveNiche from './alcoveNiche.js';
import alembicSet from './alembicSet.js';
import altarDark from './altarDark.js';
import altarStone from './altarStone.js';
import amphoraTall from './amphoraTall.js';
import anvilIron from './anvilIron.js';
import anvilStone from './anvilStone.js';
import archLiningPiece from './archLiningPiece.js';
import armorStand from './armorStand.js';
import arrowTarget from './arrowTarget.js';
import ashesPile from './ashesPile.js';
import ballistaRemnant from './ballistaRemnant.js';
import bannerHalfTorn from './bannerHalfTorn.js';
import bannerHerald from './bannerHerald.js';
import bannerLong from './bannerLong.js';
import bannerNiche from './bannerNiche.js';
import bannerTorn from './bannerTorn.js';
import barrelRainwater from './barrelRainwater.js';
import barrelStack from './barrelStack.js';
import barrelWood from './barrelWood.js';
import barricadeWood from './barricadeWood.js';
import basketWicker from './basketWicker.js';
import bedFourPoster from './bedFourPoster.js';
import bedRoll from './bedRoll.js';
import benchHall from './benchHall.js';
import benchStone from './benchStone.js';
import benchWood from './benchWood.js';
import blindArcade from './blindArcade.js';
import bloodStain from './bloodStain.js';
import boneScatter from './boneScatter.js';
import bonesBound from './bonesBound.js';
import bonfireRemnant from './bonfireRemnant.js';
import bookStack from './bookStack.js';
import bottleCase from './bottleCase.js';
import bottleRack from './bottleRack.js';
import boulderMossy from './boulderMossy.js';
import bookcaseTall from './bookcaseTall.js';
import bowRack from './bowRack.js';
import brazierDish from './brazierDish.js';
import brazierFire from './brazierFire.js';
import breadBasket from './breadBasket.js';
import buttressWall from './buttressWall.js';
import candelabraFloor from './candelabraFloor.js';
import candelabraTable from './candelabraTable.js';
import candleAltarCircle from './candleAltarCircle.js';
import candleBurntOut from './candleBurntOut.js';
import candleStand from './candleStand.js';
import catapultBroken from './catapultBroken.js';
import cauldronWitch from './cauldronWitch.js';
import censerChain from './censerChain.js';
import chairHighback from './chairHighback.js';
import chairSimple from './chairSimple.js';
import chandelierChain from './chandelierChain.js';
import cheeseWheels from './cheeseWheels.js';
import chestLarge from './chestLarge.js';
import chestLocked from './chestLocked.js';
import chestTreasure from './chestTreasure.js';
import churnButter from './churnButter.js';
import circleSummon from './circleSummon.js';
import cloakHook from './cloakHook.js';
import cobwebCorner from './cobwebCorner.js';
import coatRackWood from './coatRackWood.js';
import coinScatter from './coinScatter.js';
import columnBasalt from './columnBasalt.js';
import columnRound from './columnRound.js';
import corbelSupport from './corbelSupport.js';
import cotBed from './cotBed.js';
import cracksFloor from './cracksFloor.js';
import cradleWood from './cradleWood.js';
import crateLong from './crateLong.js';
import crateStack from './crateStack.js';
import crateWood from './crateWood.js';
import crossedSwords from './crossedSwords.js';
import crystalCluster from './crystalCluster.js';
import crystalLamp from './crystalLamp.js';
import cupboardClosed from './cupboardClosed.js';
import curtainDraped from './curtainDraped.js';
import deskScribe from './deskScribe.js';
import feathersScatter from './feathersScatter.js';
import fireplaceBig from './fireplaceBig.js';
import flourSack from './flourSack.js';
import fontStone from './fontStone.js';
import fountainDry from './fountainDry.js';
import garlandDried from './garlandDried.js';
import gobletPair from './gobletPair.js';
import graveShallow from './graveShallow.js';
import gravelPatch from './gravelPatch.js';
import hayScatter from './hayScatter.js';
import hearthStone from './hearthStone.js';
import hooksRope from './hooksRope.js';
import hornMounted from './hornMounted.js';
import hourglassStand from './hourglassStand.js';
import idolSmall from './idolSmall.js';
import jarSmall from './jarSmall.js';
import kettleTripod from './kettleTripod.js';
import ladderLean from './ladderLean.js';
import lanternFloor from './lanternFloor.js';
import lanternWall from './lanternWall.js';
import lecternPodium from './lecternPodium.js';
import logPile from './logPile.js';
import mapTable from './mapTable.js';
import meatRackHang from './meatRackHang.js';
import mirrorAntique from './mirrorAntique.js';
import mossPatchFloor from './mossPatchFloor.js';
import mountedHead from './mountedHead.js';
import mushroomsGlow from './mushroomsGlow.js';
import nestRafters from './nestRafters.js';
import oilLampStand from './oilLampStand.js';
import orbStand from './orbStand.js';
import orreryMini from './orreryMini.js';
import paintingGrand from './paintingGrand.js';
import paintingTilted from './paintingTilted.js';
import pantryShelf from './pantryShelf.js';
import pilasterHalf from './pilasterHalf.js';
import pillarWooden from './pillarWooden.js';
import pillowPile from './pillowPile.js';
import plankRepair from './plankRepair.js';
import plantHanging from './plantHanging.js';
import plantPotDead from './plantPotDead.js';
import plaqueEngraved from './plaqueEngraved.js';
import platesStack from './platesStack.js';
import potHerb from './potHerb.js';
import potIron from './potIron.js';
import potionShelf from './potionShelf.js';
import prieDieu from './prieDieu.js';
import puddleWater from './puddleWater.js';
import reliefBattle from './reliefBattle.js';
import reliefSigil from './reliefSigil.js';
import reliquaryBox from './reliquaryBox.js';
import ritualCircle from './ritualCircle.js';
import rootsCreep from './rootsCreep.js';
import ropeCoil from './ropeCoil.js';
import rubblePile from './rubblePile.js';
import rubbleScatter from './rubbleScatter.js';
import rugWorn from './rugWorn.js';
import runesScratch from './runesScratch.js';
import sackOpen from './sackOpen.js';
import sacksGrain from './sacksGrain.js';
import sconceCandle from './sconceCandle.js';
import screenFolding from './screenFolding.js';
import scrollRolls from './scrollRolls.js';
import shelfLadderStep from './shelfLadderStep.js';
import shieldStack from './shieldStack.js';
import shieldWall from './shieldWall.js';
import sideTableNarrow from './sideTableNarrow.js';
import skullPile from './skullPile.js';
import spearBundle from './spearBundle.js';
import specimenJar from './specimenJar.js';
import spikesGround from './spikesGround.js';
import spoutFountainWall from './spoutFountainWall.js';
import staffRack from './staffRack.js';
import stalagmite from './stalagmite.js';
import statuePedestal from './statuePedestal.js';
import stoolSquare from './stoolSquare.js';
import stoolThree from './stoolThree.js';
import strawBedding from './strawBedding.js';
import stumpTree from './stumpTree.js';
import symbolFaith from './symbolFaith.js';
import tableLong from './tableLong.js';
import tableRound from './tableRound.js';
import tableWood from './tableWood.js';
import tableWriting from './tableWriting.js';
import tapestryGrand from './tapestryGrand.js';
import tatteredCloth from './tatteredCloth.js';
import throneSmall from './throneSmall.js';
import tilesUplift from './tilesUplift.js';
import tomeChained from './tomeChained.js';
import toolRackSmith from './toolRackSmith.js';
import toolWallBoard from './toolWallBoard.js';
import torchSerpent from './torchSerpent.js';
import torchStanding from './torchStanding.js';
import trainingDummy from './trainingDummy.js';
import urnLidded from './urnLidded.js';
import vaseClay from './vaseClay.js';
import vaseTwinEar from './vaseTwinEar.js';
import vialRack from './vialRack.js';
import wallColumnStrip from './wallColumnStrip.js';
import wallGapRuin from './wallGapRuin.js';
import wallTorch from './wallTorch.js';
import wardrobeTall from './wardrobeTall.js';
import waterBasin from './waterBasin.js';
import waxDrips from './waxDrips.js';
import weaponCart from './weaponCart.js';
import weaponRack from './weaponRack.js';
import wellIndoor from './wellIndoor.js';
import wineRackWall from './wineRackWall.js';

const propRegistry = new Map();

function register(def) {
  if (!def?.id) throw new Error('props: 登记项缺 id');
  if (propRegistry.has(def.id)) throw new Error(`props: 重复登记 "${def.id}"`);
  propRegistry.set(def.id, def);
}

register(alcoveNiche);
register(alembicSet);
register(altarDark);
register(altarStone);
register(amphoraTall);
register(anvilIron);
register(anvilStone);
register(archLiningPiece);
register(armorStand);
register(arrowTarget);
register(ashesPile);
register(ballistaRemnant);
register(bannerHalfTorn);
register(bannerHerald);
register(bannerLong);
register(bannerNiche);
register(bannerTorn);
register(barrelRainwater);
register(barrelStack);
register(barrelWood);
register(barricadeWood);
register(basketWicker);
register(bedFourPoster);
register(bedRoll);
register(benchHall);
register(benchStone);
register(benchWood);
register(blindArcade);
register(bloodStain);
register(boneScatter);
register(bonesBound);
register(bonfireRemnant);
register(bookStack);
register(bottleCase);
register(bottleRack);
register(boulderMossy);
register(bowRack);
register(brazierDish);
register(brazierFire);
register(breadBasket);
register(buttressWall);
register(candelabraFloor);
register(candelabraTable);
register(candleAltarCircle);
register(candleBurntOut);
register(candleStand);
register(catapultBroken);
register(cauldronWitch);
register(censerChain);
register(chairHighback);
register(chairSimple);
register(chandelierChain);
register(cheeseWheels);
register(chestLarge);
register(chestLocked);
register(chestTreasure);
register(churnButter);
register(circleSummon);
register(cloakHook);
register(cobwebCorner);
register(coatRackWood);
register(coinScatter);
register(columnBasalt);
register(columnRound);
register(corbelSupport);
register(cotBed);
register(cracksFloor);
register(cradleWood);
register(crateLong);
register(crateStack);
register(crateWood);
register(crossedSwords);
register(crystalCluster);
register(crystalLamp);
register(cupboardClosed);
register(curtainDraped);
register(deskScribe);
register(feathersScatter);
register(fireplaceBig);
register(flourSack);
register(fontStone);
register(fountainDry);
register(garlandDried);
register(gobletPair);
register(graveShallow);
register(gravelPatch);
register(hayScatter);
register(hearthStone);
register(hooksRope);
register(hornMounted);
register(hourglassStand);
register(idolSmall);
register(jarSmall);
register(kettleTripod);
register(ladderLean);
register(lanternFloor);
register(lanternWall);
register(lecternPodium);
register(logPile);
register(mapTable);
register(meatRackHang);
register(mirrorAntique);
register(mossPatchFloor);
register(mountedHead);
register(mushroomsGlow);
register(nestRafters);
register(oilLampStand);
register(orbStand);
register(orreryMini);
register(paintingGrand);
register(paintingTilted);
register(pantryShelf);
register(pilasterHalf);
register(pillarWooden);
register(pillowPile);
register(plankRepair);
register(plantHanging);
register(plantPotDead);
register(plaqueEngraved);
register(platesStack);
register(potHerb);
register(potIron);
register(potionShelf);
register(prieDieu);
register(puddleWater);
register(reliefBattle);
register(reliefSigil);
register(reliquaryBox);
register(ritualCircle);
register(rootsCreep);
register(ropeCoil);
register(rubblePile);
register(rubbleScatter);
register(rugWorn);
register(runesScratch);
register(sackOpen);
register(sacksGrain);
register(sconceCandle);
register(screenFolding);
register(scrollRolls);
register(shelfLadderStep);
register(shieldStack);
register(shieldWall);
register(sideTableNarrow);
register(skullPile);
register(spearBundle);
register(specimenJar);
register(spikesGround);
register(spoutFountainWall);
register(staffRack);
register(stalagmite);
register(statuePedestal);
register(stoolSquare);
register(stoolThree);
register(strawBedding);
register(stumpTree);
register(symbolFaith);
register(tableLong);
register(tableRound);
register(tableWood);
register(tableWriting);
register(tapestryGrand);
register(tatteredCloth);
register(throneSmall);
register(tilesUplift);
register(tomeChained);
register(toolRackSmith);
register(toolWallBoard);
register(torchSerpent);
register(torchStanding);
register(trainingDummy);
register(urnLidded);
register(vaseClay);
register(vaseTwinEar);
register(vialRack);
register(wallColumnStrip);
register(wallGapRuin);
register(wallTorch);
register(wardrobeTall);
register(waterBasin);
register(waxDrips);
register(weaponCart);
register(weaponRack);
register(wellIndoor);
register(wineRackWall);

/** 全部已登记资产（id → 契约对象）。 */
export { propRegistry };

/** 按 id 取资产定义；不存在抛错（拼写错误宁可炸）。 */
export function getProp(id) {
  const def = propRegistry.get(id);
  if (!def) throw new Error(`props: 未登记的资产 "${id}"`);
  return def;
}
