// 卡图键生成器：按「晋升链 + 同名合并」把系列粗键拆成链级细键。
//   口径（用户 2026-09-22 定）：同晋升链/同名 = 同键（升级共享基础图 + 等阶变体渐强）；
//   异链异名 = 异键（每张卡独一无二，方便辨别）。
// 用法：node tools/genArtKeys.mjs
// 产物：① src/core/skills/artKeys.js（覆盖表，content/index.js 尾部 applyArtKeyOverrides() 应用）
//       ② tmp/art_chains.txt（键→链 审计表，写 prompt 用）
import '../src/core/content/index.js';
import { allSkills } from '../src/core/skills/registry.js';
import { ART_KEY_OVERRIDES as CURRENT } from '../src/core/skills/artKeys.js';
import { writeFileSync } from 'node:fs';

const TIER_IDX = { D: 0, C: 1, B: 2, A: 3, S: 4 };
const SKIP_KEYS = new Set(['normal-1']); // GM 调试卡不需要卡图

const defs = allSkills();
const byId = new Map(defs.map(d => [d.id, d]));
// keyOf 读**原创键**（先扣掉当前表写进 def.image 的覆盖值）：applyArtKeyOverrides 在
// content 加载尾部已应用本表——直接读 image 会让每个已拆键各自成单链组、按「单链不动」
// 被跳过，二次再生就把旧表洗没（2026-09-28 幂等修复，美术大挂的根因）。
// 还原口径：image === 当前表值 → 属覆盖写入，取 _image0（apply 留档的原创值）或回落 series。
const keyOf = (d) => {
  const t = CURRENT[d.id];
  const authored = (t !== undefined && d.image === t) ? (d._image0 ?? undefined) : d.image;
  return authored ?? d.series ?? `${d.type}-${TIER_IDX[d.tier] ?? '?'}`;
};

// —— 按自然键分组 ——
const byKey = new Map();
for (const d of defs) {
  const k = keyOf(d);
  if (!byKey.has(k)) byKey.set(k, []);
  byKey.get(k).push(d);
}

// —— 组内晋升链（只跟 promotesTo；battlePromotesTo 是局内转化，目标卡本身也单独立键） ——
function buildChains(cards) {
  const ids = new Set(cards.map(d => d.id));
  const parent = new Map();
  for (const d of cards) {
    for (const t of [].concat(d.promotesTo ?? [])) if (ids.has(t)) parent.set(t, d.id);
  }
  const roots = cards.filter(d => !parent.has(d.id));
  const chains = [];
  const seen = new Set();
  for (const r of roots) {
    const chain = [];
    let cur = r;
    while (cur && !seen.has(cur.id)) {
      seen.add(cur.id);
      chain.push(cur);
      const nxt = [].concat(cur.promotesTo ?? []).map(t => byId.get(t)).find(d => d && ids.has(d.id) && !seen.has(d.id));
      cur = nxt;
    }
    if (chain.length) chains.push(chain);
  }
  for (const d of cards) if (!seen.has(d.id)) { chains.push([d]); seen.add(d.id); }
  return chains;
}

// —— 同名合并（并查集）：同名即同卡（含敌我双版/晋升缺链），共享一键 ——
function mergeByName(chains) {
  const par = chains.map((_, i) => i);
  const find = (i) => (par[i] === i ? i : (par[i] = find(par[i])));
  const byName = new Map();
  chains.forEach((ch, i) => {
    for (const d of ch) {
      if (!byName.has(d.name)) byName.set(d.name, i);
      else { const a = find(i), b = find(byName.get(d.name)); if (a !== b) par[a] = b; }
    }
  });
  const groups = new Map();
  chains.forEach((ch, i) => {
    const r = find(i);
    if (!groups.has(r)) groups.set(r, []);
    groups.get(r).push(ch);
  });
  return [...groups.values()].map((gs) => {
    const cards = gs.flat();
    // 键 = 最长链根 id（并列取先见）
    const longest = [...gs].sort((a, b) => b.length - a.length)[0];
    return { key: longest[0].id, chains: gs, cards };
  });
}

const overrides = {};
const report = [];
let splitKeys = 0, newKeys = 0;
for (const [key, cards] of [...byKey.entries()].sort()) {
  if (SKIP_KEYS.has(key)) continue;
  const groups = mergeByName(buildChains(cards));
  if (groups.length <= 1) continue; // 单链系列不动：系列键继续服务
  splitKeys++;
  newKeys += groups.length;
  report.push(`\n== ${key} → ${groups.length} 键 ==`);
  for (const g of [...groups].sort((a, b) => a.key.localeCompare(b.key))) {
    const sig = g.chains.map(ch => ch.map(d => `${d.name}(${d.tier})`).join('→')).join(' ＋ ');
    report.push(`  ${g.key} ⇒ ${sig}`);
    for (const d of g.cards) {
      overrides[d.id] = g.key;
      let desc = '';
      try { desc = typeof d.describe === 'function' ? d.describe() : ''; } catch { desc = ''; }
      report.push(`      ${d.id}｜${d.name}｜${d.tier}｜${desc.replace(/\s+/g, ' ').slice(0, 60)}`);
    }
  }
}

const table = Object.entries(overrides).sort((a, b) => a[1].localeCompare(b[1]) || a[0].localeCompare(b[0]));
const js = `// 卡图键覆盖表（GENERATED by tools/genArtKeys.mjs —— 内容增删卡后重跑该脚本再生，勿手改）。
// 口径（用户 2026-09-22 定）：同晋升链/同名 = 同键（升级共享基础图，等阶变体渐强）；
// 异链异名 = 异键（每张卡独一无二）。覆盖 = 给 def.image 赋值；未列入的卡维持 series 键解析。
import { allSkills } from './registry.js';

// 导出给 genArtKeys.mjs：再生时先扣掉本表再按自然键分组（幂等，见 apply 注释）
export const ART_KEY_OVERRIDES = {
${table.map(([id, k]) => `  ${JSON.stringify(id)}: ${JSON.stringify(k)},`).join('\n')}
};

// 内容登记完毕后调用一次（content/index.js 尾部）：把链级键写进 def.image。
// 原创键留档 _image0（2026-09-28 幂等修复）：genArtKeys 二次再生时按「表值≠自然键」
// 还原分组——否则直接读 def.image 会让每个已拆键各自成单链组被跳过，旧表被洗没
//（美术大挂的根因）。
export function applyArtKeyOverrides() {
  for (const def of allSkills()) {
    const k = ART_KEY_OVERRIDES[def.id];
    if (k && def.image !== k) {
      if (def.image != null) def._image0 ??= def.image;
      def.image = k;
    }
  }
}
`;
writeFileSync('src/core/skills/artKeys.js', js, 'utf8');
writeFileSync('tmp/art_chains.txt', report.join('\n') + '\n', 'utf8');
console.log(`拆分 ${splitKeys} 系列 → ${newKeys} 链键；覆盖 ${table.length} 卡`);
console.log('→ src/core/skills/artKeys.js ｜ → tmp/art_chains.txt');
